In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
from sklearn.datasets import load_iris

In [3]:
df = pd.read_csv('Titanic-Dataset.csv')
df.head()
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [11]:
# the ml pipeline 
# data cleaning -> train test split -> feature engineering -> model training -> model prediction -> model evaluation -> model deployment

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [15]:
# cleaning the data
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df = df.drop(columns=["Cabin","Name","Ticket","PassengerId"])
print(df.head())
print(df.info())

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(2)
memory usage: 60.9 KB
None

In [29]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df.dropna(subset=['Embarked'], inplace=True)

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    str
 4   Sex          889 non-null    str
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    str
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 125.8 KB

In [27]:
# feature and target variable
X = df.drop(columns=['Survived'])
y = df['Survived']

In [28]:
X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x = df.drop(columns=['Survived']) # independent features
y = df['Survived'] # dependent features
print(x.head(1))
print(y.head(1))
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42,)

   PassengerId  Pclass                     Name   Sex   Age  SibSp  Parch  \
0            1       3  Braund, Mr. Owen Harris  male  22.0      1      0

      Ticket  Fare Cabin Embarked
0  A/5 21171  7.25   NaN        S
0    0
Name: Survived, dtype: int64

ValueError: could not convert string to float: 'Partner, Mr. Austen'

In [14]:
cat_cols = ['Sex','Embarked']

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

In [15]:
ct = ColumnTransformer([('cat', OneHotEncoder(sparse_output=False), cat_cols)],remainder='passthrough')
x_train_final = ct.fit_transform(x_train)
x_test_final = ct.transform(x_test)

In [41]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train_final,y_train)

ValueError: could not convert string to float: 'Partner, Mr. Austen'

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
x_train.shape
x_train_final.shape

(712, 15)

In [31]:
model = KNeighborsClassifier()
model.fit(x_train_final,y_train)
y_pre = model.predict(x_test_final)
print(accuracy_score(y_test,y_pre))
print(y_pre)

ValueError: could not convert string to float: 'Partner, Mr. Austen'

In [20]:
x_train.describe().loc[['min','max']]

     PassengerId  Pclass    Age  SibSp  Parch      Fare
min          1.0     1.0   0.42    0.0    0.0    0.0000
max        891.0     3.0  80.00    8.0    6.0  512.3292

In [24]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
x_train_final_scaled = scaler.fit_transform(x_train_final)
x_test_final_scaled = scaler.transform(x_test_final)

ValueError: could not convert string to float: 'Partner, Mr. Austen'

In [42]:
scaled_model = KNeighborsClassifier()
scaled_model.fit(x_train_final_scaled,y_train)
y_pred = scaled_model.predict(x_test_final_scaled)
print(accuracy_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred_scaled_final))

NameError: name 'x_train_final_scaled' is not defined