In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/ankushkumar/AI-Ml/Machine Learning/class-01/placement.csv')      # syntax examples
food = pd.read_csv('/Users/ankushkumar/AI-Ml/Machine Learning/class-01/food_orders.csv')
df.head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
4,VS2670,5.63,88.3,CSE,2.0,2,0,132.0,6.3,No,Yes,5.22

In [3]:
food.head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
0,ORD10591,Mumbai,Chinese,Thu,22,3,4.5,519,27,Card,NaN,15.0,No
1,ORD10520,Pune,Chinese,Sat,14,1,14.0,295,60,Cash,3.0,15.0,Yes
2,ORD10588,Hyderabad,Chinese,Sat,22,3,11.8,744,44,UPI,3.0,NaN,Yes
3,ORD10113,Delhi,Desserts,Mon,22,3,5.2,370,36,UPI,5.0,20.0,No
4,ORD10322,Delhi,Burger,Fri,14,4,7.2,594,29,UPI,5.0,10.0,No

In [4]:
# 1. First look
df.shape

(550, 12)

In [5]:
df.describe().round(2)

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score,package_lpa
count,550.00,550.00,519.00,550.00,550.00,454.00,538.00,517.00
mean,7.36,77.60,1.30,2.56,0.68,153.15,6.27,4.71
std,0.98,10.12,1.18,1.49,1.10,86.06,1.69,3.48
min,5.00,55.00,0.00,0.00,0.00,16.00,1.10,0.00
25%,6.69,70.90,0.00,1.00,0.00,90.00,5.20,0.00
50%,7.40,77.90,1.00,2.00,0.00,134.00,6.30,6.01
75%,7.98,84.50,2.00,4.00,1.00,192.75,7.40,7.28
max,10.00,98.00,4.00,6.00,4.00,500.00,10.00,12.56

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           550 non-null    str
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    str
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64
 6   backlogs             550 non-null    int64
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    str
 10  placed               550 non-null    str
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 59.4 KB

In [7]:
# Q1. How many orders are in the file, and how many details are stored for each order?
print(food.shape)

(612, 13)

In [8]:
food.head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
0,ORD10591,Mumbai,Chinese,Thu,22,3,4.5,519,27,Card,NaN,15.0,No
1,ORD10520,Pune,Chinese,Sat,14,1,14.0,295,60,Cash,3.0,15.0,Yes
2,ORD10588,Hyderabad,Chinese,Sat,22,3,11.8,744,44,UPI,3.0,NaN,Yes
3,ORD10113,Delhi,Desserts,Mon,22,3,5.2,370,36,UPI,5.0,20.0,No
4,ORD10322,Delhi,Burger,Fri,14,4,7.2,594,29,UPI,5.0,10.0,No

In [9]:
# Q2. Someone ordered food worth a small EMI. Find the biggest order value and the longest delivery time using one command.
print(food[['order_value', 'delivery_time_min']].max())

order_value          2354
delivery_time_min      63
dtype: int64

In [10]:
# Q3. Which columns hold numbers and which hold text?
print(food.dtypes)

order_id                 str
city                     str
cuisine                  str
day                      str
order_hour             int64
quantity               int64
distance_km          float64
order_value            int64
delivery_time_min      int64
payment                  str
rating               float64
tip                  float64
was_late                 str
dtype: object

In [11]:
# 2. Selecting
df['cgpa']

0      7.41
1      7.52
2      7.35
3      7.86
4      5.63
       ...
545    8.40
546    7.60
547    6.33
548    8.86
549    8.45
Name: cgpa, Length: 550, dtype: float64

In [12]:
# many columns: a list inside [ ]
df[['branch', 'cgpa', 'placed']].head()

  branch  cgpa placed
0     IT  7.41     No
1    CSE  7.52    Yes
2    CSE  7.35    Yes
3    CSE  7.86    Yes
4    CSE  5.63    Yes

In [13]:
# iloc: by position -> rows, columns
df.iloc[0:5, 0:3]

  student_id  cgpa  twelfth_percent
0     VS2821  7.41             78.5
1     VS3068  7.52             70.0
2     VS2940  7.35             78.3
3     VS3138  7.86             60.2
4     VS2670  5.63             88.3

In [14]:
# loc: by label -> rows, column names (both ends included)
df.loc[0:4, 'cgpa':'internships']

   cgpa  twelfth_percent branch  internships
0  7.41             78.5     IT          0.0
1  7.52             70.0    CSE          2.0
2  7.35             78.3    CSE          2.0
3  7.86             60.2    CSE          1.0
4  5.63             88.3    CSE          2.0

In [15]:
# Q4. The manager's eyes hurt after 13 columns. Show only city, cuisine and order_value for the first 10 orders.
print(food[['city', 'cuisine', 'order_value']].head(10))

        city       cuisine  order_value
0     Mumbai       Chinese          519
1       Pune       Chinese          295
2  Hyderabad       Chinese          744
3      Delhi      Desserts          370
4      Delhi        Burger          594
5     Mumbai       Biryani          933
6  Hyderabad  South Indian          197
7       Pune       Biryani         1482
8  Bangalore       Biryani          522
9       Pune  South Indian          233

In [16]:
# Q5. The printer jammed and printed only rows 50 to 54, first 5 columns. Recreate that page using positions.

print(food.iloc[50:55, 0:5])

    order_id       city       cuisine  day  order_hour
50  ORD10161  Bangalore         Pizza  Sun          22
51  ORD10156       Pune      Desserts  Mon          21
52  ORD10160      Delhi      Desserts  Sat          20
53  ORD10310       Pune      Desserts  Sun          13
54  ORD10018     Mumbai  South Indian  Sat          18

In [17]:
# Q6. Using labels, show rows 100 to 105 and every column from city to order_hour.
print(food.loc[100:105, 'city':'order_hour'])

          city       cuisine  day  order_hour
100       Pune       Biryani  Sat          12
101       Pune        Burger  Sun          21
102     Mumbai         Pizza  Thu          17
103  Bangalore       Biryani  Sun          19
104     Mumbai         Pizza  Sun          23
105     Mumbai  South Indian  Sun          13

In [18]:
# 3. Filtering and sorting
# one condition
df[df['cgpa'] > 8]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
14,VS2701,9.01,64.8,ECE,1.0,0,1,NaN,4.8,Yes,Yes,6.70
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
18,VS2936,8.23,69.5,CSE,3.0,3,1,119.0,6.9,Yes,Yes,8.54
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
...,...,...,...,...,...,...,...,...,...,...,...,...
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
539,VS2966,8.45,80.9,Mech,2.0,2,1,90.0,7.6,No,Yes,7.31
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [19]:
# two conditions: & is and, | is or, each in its own ( )
df[(df['cgpa'] > 8) & (df['backlogs'] == 0)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
44,VS3139,8.85,81.2,Mech,0.0,3,0,194.0,7.4,No,Yes,6.89
47,VS2788,8.09,84.6,Mech,0.0,2,0,220.0,6.0,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
534,VS3112,8.37,63.9,CSE,4.0,2,0,103.0,5.9,Yes,Yes,7.52
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [20]:
# value is one of many
df[df['branch'].isin(['CSE', 'IT'])]

# value inside a range (both ends included)
df[df['cgpa'].between(7, 8)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
6,VS2971,7.79,74.7,CSE,0.0,4,0,NaN,7.3,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
536,VS3032,7.53,83.5,ECE,0.0,2,3,20.0,6.7,No,No,0.00
542,VS2998,7.81,63.4,IT,4.0,4,0,89.0,5.1,Yes,Yes,8.52
543,VS2785,7.19,77.5,ECE,3.0,4,0,84.0,6.5,No,Yes,6.68
544,VS2948,7.18,87.2,ECE,NaN,1,1,296.0,4.2,Yes,No,0.00
546,VS3102,7.60,76.5,Civil,0.0,4,0,NaN,6.7,Yes,Yes,5.68

In [21]:
# count of each category
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [22]:
# sort, biggest first
df.sort_values('cgpa', ascending=False).head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
113,VS3148,10.00,93.9,Mech,3.0,3,0,190.0,6.8,Yes,Yes,9.17
500,VS2917,10.00,84.0,ECE,0.0,4,0,58.0,6.3,No,Yes,8.54
265,VS2702,9.95,86.5,CSE,2.0,0,0,248.0,7.0,No,Yes,10.03
185,VS3124,9.85,63.8,CSE,0.0,4,0,87.0,7.5,Yes,Yes,8.77
157,VS2747,9.78,85.3,ECE,2.0,2,0,NaN,5.3,Yes,Yes,NaN

In [23]:
# Q7. Biryani at 2 AM is not hunger, it is a lifestyle. Count the Biryani orders placed between midnight and 3 AM (hours 0 to 3).
print(food[(food['cuisine'] == 'Biryani') & (food['order_hour'].between(0, 3))].shape[0])

35

In [24]:
# Q8. Someone in Pune is clearly throwing a party. Show Pune orders worth more than 1000 rupees. How many?
print(food[(food['city'] == 'Pune') & (food['order_value'] > 1000)].shape[0])

23

In [25]:
# Q9. A food blogger survives only on Pizza and Burger. How many such orders are there?

print(food[food['cuisine'].isin(['Pizza', 'Burger'])].shape[0])

190

In [26]:
# Q10. How many deliveries fell in the "bhaiya, kahan ho?" zone of 30 to 45 minutes?
print(food[food['delivery_time_min'].between(30, 45)].shape[0])

222

In [27]:
food.head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
0,ORD10591,Mumbai,Chinese,Thu,22,3,4.5,519,27,Card,NaN,15.0,No
1,ORD10520,Pune,Chinese,Sat,14,1,14.0,295,60,Cash,3.0,15.0,Yes
2,ORD10588,Hyderabad,Chinese,Sat,22,3,11.8,744,44,UPI,3.0,NaN,Yes
3,ORD10113,Delhi,Desserts,Mon,22,3,5.2,370,36,UPI,5.0,20.0,No
4,ORD10322,Delhi,Burger,Fri,14,4,7.2,594,29,UPI,5.0,10.0,No

In [28]:
# Q11. Does anyone still pay in cash? Count the orders by payment method.
print(food['payment'].value_counts())

payment
UPI     363
Card    154
Cash     95
Name: count, dtype: int64

In [29]:
# Q12. Someone definitely ordered for the whole hostel. Show the 5 biggest orders with city, cuisine, quantity and order_value.
print(food[['city', 'cuisine', 'quantity', 'order_value']].sort_values('order_value', ascending=False).head(5))

          city  cuisine  quantity  order_value
586  Hyderabad  Biryani         8         2354
544  Hyderabad  Biryani         8         2254
476     Mumbai  Biryani         8         2114
367       Pune  Biryani         8         1944
388  Hyderabad  Biryani         6         1895

In [30]:
# Q13. Which delivery partners were basically The Flash? Show the 5 fastest deliveries with city, distance_km and delivery_time_min.

print(food[['city', 'distance_km', 'delivery_time_min']].sort_values('delivery_time_min').head(5))

          city  distance_km  delivery_time_min
325       Pune          1.2                  8
580       Pune          1.4                  8
480      Delhi          1.0                  8
121  Hyderabad          1.3                  8
458      Delhi          1.4                  9

In [31]:
# 4. Cleaning
# blanks per column
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [32]:
# repeated rows
print(df.duplicated().sum())

# remove repeated rows
df_clean = df.drop_duplicates()

0

In [33]:
# remove rows where one column is blank
df_clean = df_clean.dropna(subset=['internships'])

# fill blanks with a value
df_clean['prep_hours'] = df_clean['prep_hours'].fillna(0)

# change the type
df_clean['internships'] = df_clean['internships'].astype(int)

In [34]:
# new column from existing columns
df_clean['cgpa_percent'] = (df_clean['cgpa'] * 9.5).round(1)
df_clean[['cgpa', 'cgpa_percent']].head()

   cgpa  cgpa_percent
0  7.41          70.4
1  7.52          71.4
2  7.35          69.8
3  7.86          74.7
4  5.63          53.5

In [35]:
# Q14. Count the blanks in every column.

print(food.isnull().sum())

order_id               0
city                   0
cuisine                0
day                    0
order_hour             0
quantity               0
distance_km            8
order_value            0
delivery_time_min      0
payment                0
rating               107
tip                  185
was_late               0
dtype: int64

In [36]:
#  15 The app got confused and saved some orders twice. How many repeated rows are there?

print(food.duplicated().sum())

12

In [37]:
# Q16. Remove the repeated orders before customers get charged twice. Print the shape.

print(food.drop_duplicates(inplace=True))

None

In [38]:
# Q17. GPS failed for some orders, so the delivery partner took the scenic route. Remove the rows with a blank distance_km and print the shape.

print(food.dropna(subset=['distance_km'], inplace=True))

None

In [39]:
# Q18. A blank tip means no tip, and one sad delivery partner. Fill the blanks in tip with 0 and make it a whole number.

print(food['tip'].fillna(0, inplace=True))

0      15.0
1      15.0
2       0.0
3      20.0
4      10.0
       ...
607    30.0
608     0.0
609    30.0
610     0.0
611    40.0
Name: tip, Length: 593, dtype: float64

/var/folders/26/8dmzs5m57bl3f9r887j35wk80000gn/T/ipykernel_98016/3144209729.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  print(food['tip'].fillna(0, inplace=True))

In [41]:
# Q19. Add a column value_per_item: order value divided by quantity, rounded.