In [1]:
import pandas as pd

In [ ]:
t = pd.read_csv('planets.csv')

In [16]:
df = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
result = df[df['Age'] > 65][['Pclass','Name','Fare']]
print(result)

     Pclass                                  Name     Fare
33        2                 Wheadon, Mr. Edward H  10.5000
96        1             Goldschmidt, Mr. George B  34.6542
116       3                  Connors, Mr. Patrick   7.7500
493       1               Artagaveytia, Mr. Ramon  49.5042
630       1  Barkworth, Mr. Algernon Henry Wilson  30.0000
672       2           Mitchell, Mr. Henry Michael  10.5000
745       1          Crosby, Capt. Edward Gifford  71.0000
851       3                   Svensson, Mr. Johan   7.7750

In [23]:
df[~(df['Embarked'] == 'S')].shape[0]

247

In [20]:
df[(df['Age'] < 10) | (df['Age'] > 70)].shape[0]

67

In [24]:
df['Pclass'].value_counts()
df[df['Pclass'] == 3]['Sex'].value_counts()

Sex
male      347
female    144
Name: count, dtype: int64

In [29]:
df['Parch'].value_counts()
df[df['Parch'] == 0]['Sex'].value_counts()
df['Travel-group'] = "alone"
df.loc[(df['SibSp'] + df['Parch']) > 0, 'travel_group'] = 'with family'
df['Travel-group'].value_counts()

Travel-group
alone    891
Name: count, dtype: int64

In [59]:
p = pd.read_csv('/Users/ankushkumar/AI-Ml/Class/planets (1).csv')
p.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [35]:
# find the missing value
p.isnull().sum()

Planet                           0
Color                            0
Mass (10^24kg)                   0
Diameter (km)                    0
Density (kg/m^3)                 0
Surface Gravity(m/s^2)           0
Escape Velocity (km/s)           0
Rotation Period (hours)          0
Length of Day (hours)            0
Distance from Sun (10^6 km)      0
Perihelion (10^6 km)             0
Aphelion (10^6 km)               0
Orbital Period (days)            0
Orbital Velocity (km/s)          0
Orbital Inclination (degrees)    0
Orbital Eccentricity             0
Obliquity to Orbit (degrees)     0
Mean Temperature (C)             0
Surface Pressure (bars)          0
Number of Moons                  0
Ring System?                     0
Global Magnetic Field?           0
dtype: int64

In [62]:
print(p['mass'].isnull().sum())

522

In [46]:
p.dropna(inplace=True)
p.dropna().sum()

Planet                             MercuryVenusEarthMarsJupiterSaturnUranusNeptune
Color                            GreyBrown and GreyBlue, Brown Green and WhiteR...
Mass (10^24kg)                                                            2666.612
Diameter (km)                                                               400697
Density (kg/m^3)                                                             25041
Surface Gravity(m/s^2)                                                        77.9
Escape Velocity (km/s)                                                       170.7
Rotation Period (hours)                                                    -4356.9
Length of Day (hours)                                                       7127.2
Distance from Sun (10^6 km)                                                10136.2
Perihelion (10^6 km)                                                        9809.3
Aphelion (10^6 km)                                                         10463.3
Orbital Period (days)                        88224.7365.2687433110,74730,58959,800
Orbital Velocity (km/s)                                                      171.3
Orbital Inclination (degrees)                                                 18.6
Orbital Eccentricity                                                         0.482
Obliquity to Orbit (degrees)                                               381.934
Mean Temperature (C)                                                           -64
Surface Pressure (bars)                       09210.01UnknownUnknownUnknownUnknown
Number of Moons                                                                205
Ring System?                                                  NoNoNoNoYesYesYesYes
Global Magnetic Field?                                      YesNoYesNoYesYesYesYes
dtype: object

In [63]:
p.dropna(subset=['mass'])

              method  number  orbital_period    mass  distance  year
0    Radial Velocity       1         269.300   7.100     77.40  2006
1    Radial Velocity       1         874.774   2.210     56.95  2008
2    Radial Velocity       1         763.000   2.600     19.84  2011
3    Radial Velocity       1         326.030  19.400    110.62  2007
4    Radial Velocity       1         516.220  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
784  Radial Velocity       3         580.000   0.947    135.00  2012
913  Radial Velocity       1         677.800  19.800       NaN  2007
914  Radial Velocity       1           6.958   0.340       NaN  2014
915  Radial Velocity       1           5.118   0.400       NaN  2014
916  Radial Velocity       1         121.710   1.540       NaN  2014

[513 rows x 6 columns]

In [65]:
p.dropna(axis=1)

               method  number  year
0     Radial Velocity       1  2006
1     Radial Velocity       1  2008
2     Radial Velocity       1  2011
3     Radial Velocity       1  2007
4     Radial Velocity       1  2009
...               ...     ...   ...
1030          Transit       1  2006
1031          Transit       1  2007
1032          Transit       1  2007
1033          Transit       1  2008
1034          Transit       1  2008

[1035 rows x 3 columns]

In [68]:
p['mass'].fillna(0)
p['mass'].fillna(p['mass'].mean())
p['mass'].fillna(p['mass'].median())
p['mass'].fillna(0).isnull().sum()

np.int64(0)

In [74]:
p.duplicated().sum()
df.duplicated().sum()
t.duplicated().sum()

np.int64(0)

In [77]:
p.drop_duplicates()

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1031 rows x 6 columns]

In [83]:
ans = p.drop_duplicates(subset=['method'],ignore_index=True)
print(ans)

                          method  number  orbital_period  mass  distance  year
0                Radial Velocity       1      269.300000  7.10     77.40  2006
1                        Imaging       1             NaN   NaN     45.52  2005
2      Eclipse Timing Variations       1    10220.000000  6.05       NaN  2009
3                        Transit       1        1.508956   NaN       NaN  2008
4                     Astrometry       1      246.360000   NaN     20.77  2013
5      Transit Timing Variations       2      160.000000   NaN   2119.00  2011
6  Orbital Brightness Modulation       2        0.240104   NaN   1180.00  2011
7                   Microlensing       1             NaN   NaN       NaN  2008
8                  Pulsar Timing       3       25.262000   NaN       NaN  1992
9    Pulsation Timing Variations       1     1170.000000   NaN       NaN  2007

In [3]:
# quetsion 1
#

In [11]:
import numpy as np
import pandas as pd
df = pd.read_csv('Titanic-Dataset.csv')
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
titanic = pd.read_csv('/Users/ankushkumar/AI-Ml/Class/Titanic-Dataset.csv')
tip = pd.read_csv('/Users/ankushkumar/AI-Ml/Class/tips.csv')

In [26]:
tip.groupby('day').size()
tip.groupby('day')['tip'].mean().round(2)
tip.groupby('day')['tip'].median().round(2)

day
Fri     3.00
Sat     2.75
Sun     3.15
Thur    2.30
Name: tip, dtype: float64

In [28]:
tip_act = tip.groupby('day')['tip'].mean()
tip_sum = tip.groupby('day')['tip'].sum()
print(tip_act)

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [33]:
tip['tip_pct'] = round(tip['tip'] / tip['total_bill']*100,2)
tip.head(2)
tip.groupby('day')['tip_pct'].mean().round(2)

day
Fri     16.99
Sat     15.31
Sun     16.69
Thur    16.13
Name: tip_pct, dtype: float64

In [39]:
tip.groupby('day')['tip'].mean()
tip.groupby('day').mean(numeric_only=True)
tip.groupby('day')

In [42]:
tip.groupby('day').mean(numeric_only=True)["tip"]
tip.groupby('day')['tip'].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [48]:
tip.groupby('size')['tip_pct'].mean().round(2)

size
1    21.73
2    16.57
3    15.21
4    14.59
5    14.15
6    15.62
Name: tip_pct, dtype: float64

In [50]:
tip.groupby('size')['total_bill'].mean().round(2)
tip.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_pct
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68

In [54]:
tip.groupby('day')['smoker'].value_counts()
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [59]:
titanic.groupby('Pclass')['Survived'].mean().round(2)*100

Pclass
1    63.0
2    47.0
3    24.0
Name: Survived, dtype: float64

In [62]:
titanic.groupby('Pclass')['Fare'].mean().round(2)

Pclass
1    84.15
2    20.66
3    13.68
Name: Fare, dtype: float64

In [65]:
titanic.groupby('Embarked')['Age'].mean().round(2)

Embarked
C    30.81
Q    28.09
S    29.45
Name: Age, dtype: float64