In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/ankushkumar/AI-Ml/Assessment/mpg.csv')

In [3]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [6]:
# Run .info() and .shape. Which column has missing values, and how many?
print(df.shape)
print(df.info())

(398, 9)
<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 35.9 KB
None

In [7]:
#  How many cars from each origin? Use value_counts().

df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [8]:
# Two jobs:

# horsepower has blanks. Fill them with the median.
# Drop name. In one line below, say why it cannot help the model.

df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())
df = df.drop(columns='name')

print(df.shape, "|", df.isna().sum().sum(), "missing")
df.head()

(398, 8) | 0 missing

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [9]:
X = df.drop(columns='origin')
y = df['origin']

print(X.shape, y.shape)
X.head()

(398, 7) (398,)

    mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70
2  18.0          8         318.0       150.0    3436          11.0          70
3  16.0          8         304.0       150.0    3433          12.0          70
4  17.0          8         302.0       140.0    3449          10.5          70

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0, stratify=y
)

print(X_train.shape, X_test.shape)

(318, 7) (80, 7)

In [11]:

X_train.describe().loc[['min', 'max']]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
min,9.0,3.0,68.0,46.0,1613.0,8.0,70.0
max,46.6,8.0,455.0,225.0,5140.0,24.8,82.0

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(X_train_scaled.shape, X_test_scaled.shape)

(318, 7) (80, 7)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

acc_raw = accuracy_score(y_test, knn.predict(X_test))
print(acc_raw)

0.6875

In [14]:
knn_scaled = KNeighborsClassifier()
knn_scaled.fit(X_train_scaled, y_train)

acc_scaled = accuracy_score(y_test, knn_scaled.predict(X_test_scaled))
print(acc_scaled)

0.75

In [15]:
print("without scaling:", round(acc_raw, 4))
print("with scaling:   ", round(acc_scaled, 4))
print("difference:     ", round(acc_scaled - acc_raw, 4))

without scaling: 0.6875
with scaling:    0.75
difference:      0.0625

In [16]:
for k in [1, 3, 5, 7, 9, 11, 15, 21]:
    m = KNeighborsClassifier(n_neighbors=k)
    m.fit(X_train_scaled, y_train)
    print(k, round(accuracy_score(y_test, m.predict(X_test_scaled)), 4))

1 0.7375
3 0.75
5 0.75
7 0.75
9 0.75
11 0.725
15 0.7375
21 0.725